### ISSUE TITLE
How to handle retry during query iteration

### ISSUE THREAD

**Issue by NicolaSpreafico** [objectify/objectify#322] opened 2017-02-22 07:13 UTC
Hello, 
I have a code like this

```
 Query<JobLog> query = ofy().load()
                .type(JobLog.class)
                .filter(filterPredicate);

QueryResultIterable<JobLog> jobs = query.iterable();

for (JobLog job : jobs) {
   // do something
}
```

Yesterday I got some errors caused by a datastore temporary issue and the provided block of code thrown an exception for this:

```
com.google.appengine.api.datastore.DatastoreTimeoutException: The datastore operation timed out, or the data was temporarily unavailable.
	at com.google.appengine.api.datastore.DatastoreApiHelper.translateError(DatastoreApiHelper.java:60)
	at com.google.appengine.api.datastore.DatastoreApiHelper$1.convertException(DatastoreApiHelper.java:121)
	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:97)
	at com.google.appengine.api.datastore.FutureHelper.getInternal(FutureHelper.java:76)
	at com.google.appengine.api.datastore.FutureHelper.quietGet(FutureHelper.java:36)
	at com.google.appengine.api.datastore.BaseQueryResultsSource.loadMoreEntities(BaseQueryResultsSource.java:196)
	at com.google.appengine.api.datastore.BaseQueryResultsSource.loadMoreEntities(BaseQueryResultsSource.java:170)
	at com.google.appengine.api.datastore.QueryResultIteratorImpl.ensureLoaded(QueryResultIteratorImpl.java:148)
	at com.google.appengine.api.datastore.QueryResultIteratorImpl.hasNext(QueryResultIteratorImpl.java:64)
	at com.googlecode.objectify.impl.KeysOnlyIterator.hasNext(KeysOnlyIterator.java:29)
	at com.google.common.collect.Iterators$6.next(Iterators.java:648)
	at com.google.common.collect.Iterators$6.next(Iterators.java:635)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.googlecode.objectify.impl.ChunkIterator.next(ChunkIterator.java:45)
	at com.googlecode.objectify.impl.ChunkIterator.next(ChunkIterator.java:20)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:569)
	at com.google.common.collect.Iterators$PeekingImpl.hasNext(Iterators.java:1171)
	at com.googlecode.objectify.impl.ChunkingIterator.hasNext(ChunkingIterator.java:51)
	at it.noovle.ape.project.manager.log.JobLogManager.groupBatchJobsWithCode(JobLogManager.java:326)
```

I tried a couple times again and after that the query iterator went fine.
I'm wondering which is the best practice on how to handle this kind of behaviour and retrying with a backoff or something.

If the method `hasNext` or `next` throws this exception, is it safe to call it again later in order to retry?
Or implicitly the next method (even if it fails) can skip the record which thrown the error and then continue from the second one?

I can use .iterator() instead of .iterable() in order to have more control on the iteration (so it is not implicity called by the foreach), but the main question remains on which is the proper way on how to handle temporary issue from the Datastore API.

**Comment by NicolaSpreafico** [comment] 2017-03-11 11:08
Hello,
any reply on this topic?

**Comment by eschultink** [comment] 2017-03-11 15:13
Your basic idea is correct: use an iterator rather than iterable, specifically so you can access the state of the iteration if something goes wrong. 

Wrap `iterator.next()` with a try-catch for `DatastoreTimeoutException`.  In the catch, you can repeat the query with the cursor you get from the iterator. Eg `iterator = query.startAt(iterator.getCursor()).iterator()`. 

Probably also worth applying some sort of exponential backoff, so your code reacts gracefully to timeout problems; and some max-retry threshold, so it doesn't loop forever if the issue isn't really transient.

**Comment by stickfigure** [comment] 2017-03-11 16:13
I'll consider this a feature request for "automatically retry datastore timeouts". Historically this has been a feature of the underlying low level API; maybe something changed there or maybe it only applies in certain circumstances. Or maybe it only retries a limited number of times and that was exceeded. Hard to know.

**Comment by NicolaSpreafico** [comment] 2017-03-11 17:48
I sketched something like this, in order to handle backOff I used some already built-in code offered by _Google HTTP Client API_

```
QueryResultIterator<JobLog> iterator = query.iterator();

BackOff backOff = new ExponentialBackOff();
Sleeper sleeper = Sleeper.DEFAULT;

while(iterator.hasNext()) {
    JobLog next;
    
    try {
        next = iterator.next();
    } catch (DatastoreFailureException|DatastoreTimeoutException e) {
        boolean continueBackOff;               
        try {
            continueBackOff = BackOffUtils.next(sleeper, backOff);
        } catch (InterruptedException | IOException e1) {
            // TODO
            throw e;
        }
        
        if(continueBackOff) {
            // The iteration continues from cursor
            iterator = query.startAt(iterator.getCursor()).iterator();

            // The iterator is now resetted, the while loop need to start again
            continue;
        } else {
            // End of backOff
            throw e;
        }
    }
    
    // Do something with current item
}
```

It is just a concept but I think that follows the idea that @eschultink suggested.

I have a doubt though: from the stacktrace I posted in the first message, it seems that the Exception was thrown by the `hasNext()` method, instead of the `next()` one.

So, even if in this new snippet I wrapped the backOff handling in the `next()` method, I think that the `hasNext()` should be handled too.

If this is the case, I think the the try-catch wrapper should sorround all the while loop, like this:
```
QueryResultIterator<JobLog> iterator = query.iterator();

BackOff backOff = new ExponentialBackOff();
Sleeper sleeper = Sleeper.DEFAULT;
try {
    while (iterator.hasNext()) {
        JobLog next = iterator.next();

        // Do something with current item
    }
} catch (DatastoreFailureException | DatastoreTimeoutException e) {
    boolean continueBackOff;
    try {
        continueBackOff = BackOffUtils.next(sleeper, backOff);
    } catch (InterruptedException | IOException e1) {
        // TODO
        throw e;
    }

    if (continueBackOff) {
        // The iteration continues from cursor
        iterator = query.startAt(iterator.getCursor()).iterator();
    } else {
        // End of backOff
        throw e;
    }
}
```

**Comment by NicolaSpreafico** [comment] 2017-03-13 08:06
I created a dedicated class which handle backOff internally during iteration, so it can be used w/o handling this kind of behaviour from the outside (and different methods can invoke the same code from different points).

You can create this iterator providing a configured `Query`, and after that you can call `hasNext` and `next` directly like a simple `Iterator`.

I share it with you if can be usable for concepts or ideas of the enhancement you suggested.

```
import java.util.Iterator;

import com.google.api.client.util.BackOff;
import com.google.api.client.util.ExponentialBackOff;
import com.google.api.client.util.Sleeper;
import com.google.appengine.api.datastore.DatastoreFailureException;
import com.google.appengine.api.datastore.DatastoreTimeoutException;
import com.google.appengine.api.datastore.QueryResultIterator;
import com.googlecode.objectify.cmd.Query;

class BackOffIterator<T> implements Iterator<T> {
    private Query<T> query;
    private QueryResultIterator<T> iterator;

    private BackOff backOff = new ExponentialBackOff();
    private Sleeper sleeper = Sleeper.DEFAULT;

    public BackOffIterator(Query<T> query) {
        this.query = query;
        this.iterator = query.iterator();
    }

    @Override
    public boolean hasNext() {
        while (true) {
            try {
                return this.iterator.hasNext();
            } catch (DatastoreFailureException | DatastoreTimeoutException e) {
                // Check for backOff
                ObjectifyUtils.handleBackOff(e, this.backOff, this.sleeper);

                // Reset the iterator and try again
                this.iterator = this.query.startAt(this.iterator.getCursor()).iterator();
            }
        }
    }

    @Override
    public T next() {
        while (true) {
            try {
                return this.iterator.next();
            } catch (DatastoreFailureException | DatastoreTimeoutException e) {
                // Check for backOff
                ObjectifyUtils.handleBackOff(e, this.backOff, this.sleeper);

                // Reset the iterator and try again
                this.iterator = this.query.startAt(this.iterator.getCursor()).iterator();
            }
        }
    }
}
```
```
static void handleBackOff(RuntimeException e, BackOff backOff, Sleeper sleeper) {
    LOG.log(Level.WARNING, "Datastore Error", e);

    try {
        if (!BackOffUtils.next(sleeper, backOff)) {
            // End of backOff
            throw e;
        } else {
            // BackOff did not thrown Exception, more attempts available
        }
    } catch (InterruptedException | IOException e1) {
        LOG.log(Level.SEVERE, "BackOff Error", e1);

        // Throw original exception
        throw e;
    }
}
```

I did a similar class which iterates `Keys<T>` instead of `T` (with the `.keys()` method invoked on query object), but because the behaviour of the Iterator is the same I think it is useless to share it too.

**Comment by NicolaSpreafico** [comment] 2017-03-30 14:46
Hello,
I want you to know that the concept code I posted a while ago is working fine for retrying on datastore.

Here is a stacktrace copied from an online App Engine application
![image](https://cloud.githubusercontent.com/assets/12278553/24510036/52a58c24-1568-11e7-8899-584878c6e5e0.png)

The warning log is a Datastore failure, you can see that after the log (and some backoff) the requests continues without blocking all the flow. And again after some INFO logs, the datastore gave error again.

**Comment by jschoedt** [comment] 2017-11-20 10:51
@NicolaSpreafico  I am facing the same issue when doing bulk updates. I am not sure that its the intended behavior but it looks like your code could potentially return duplicates if an exception it thrown in the next() method the iterator could return some elements that have already been processed. Correct?

**Comment by stickfigure** [comment] 2022-09-27 06:49
Gonna close this since so much is different in v6

**Closed by stickfigure** 2022-09-27 06:49 UTC
Labels: enhancement
