### ISSUE TITLE
The Cloud Datastore SDK does not currently support 'IN' filters

### ISSUE THREAD

**Issue by lukaszlenart** [objectify/objectify#441] opened 2019-12-29 12:32 UTC
After migrating to v6 I got this error, which is defined [here](https://github.com/objectify/objectify/blob/master/src/main/java/com/googlecode/objectify/impl/QueryImpl.java#L173) but at the same time there is example how to use `IN` operator in the [Query](https://github.com/objectify/objectify/blob/master/src/main/java/com/googlecode/objectify/cmd/Query.java#L24) class. I assume support for the `IN` operator will be added at some point in the future?

**Comment by stickfigure** [comment] 2019-12-29 17:03
If support for it shows up in Google's low level api (like it was in the past), then we'll add it. For now I'll consider this a documentation bug and will fix it in the next release.

**Comment by stickfigure** [comment] 2019-12-29 17:12
Fixed in docs

**Closed by stickfigure** 2019-12-29 17:12 UTC
Labels: bug

**Comment by Karthick-Kesavan** [comment] 2023-08-08 13:57
Hey @stickfigure , I'm using Objectify 6.0.4 and tried to use the in filter and I got this same error mentioned by @lukaszlenart  can you please let me know whether it is fixed or not.

**Comment by dsingh1212** [comment] 2023-11-15 09:22
Cloud Datastore has made it available for the IN and != operators.
https://cloud.google.com/datastore/docs/concepts/queries#special_query_types

Request to please implement.

**Comment by dsingh1212** [comment] 2023-11-15 09:22
@stickfigure

**Comment by stickfigure** [comment] 2023-11-15 20:15
Objectify actually supports the IN and != operators (and has for a long time); the limiting factor was the underlying SDK. If you're getting an error, it's probably because you are using an old version of the google cloud SDK. A quick immediate fix is to declare a dependency on the latest google-cloud-datastore jar, 2.17.5 at this moment:

```
		<dependency>
			<groupId>com.google.cloud</groupId>
			<artifactId>google-cloud-datastore</artifactId>
			<version>2.17.5</version>
		</dependency>
```

There will be an Objectify v6.1 released soon which updates the transitive SDK dependency to the latest version. But it's not a bad idea to specifically declare the google-cloud-datastore version in your project.

**Comment by dsingh1212** [comment] 2023-11-16 09:14
I changed from cloud-datastore from 2.11.4 to 2.17.5 and i am getting this error

SEVERE: Servlet.service() for servlet [spring-mvc] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: com.google.datastore.v1.PartitionId$Builder.setDatabaseId(Ljava/lang/String;)Lcom/google/datastore/v1/PartitionId$Builder;] with root cause
java.lang.NoSuchMethodError: com.google.datastore.v1.PartitionId$Builder.setDatabaseId(Ljava/lang/String;)Lcom/google/datastore/v1/PartitionId$Builder;

POM.xml contains 
<dependency>
            <groupId>com.googlecode.objectify</groupId>
            <artifactId>objectify</artifactId>
            <version>6.0.9</version>  
        </dependency>
       
          <dependency>
			<groupId>com.google.cloud</groupId>
			<artifactId>google-cloud-datastore</artifactId>
			<version>2.17.5</version>  
		</dependency> 
		        <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>32.1.3-jre</version>
    </dependency>

**Comment by stickfigure** [comment] 2023-11-16 15:11
NoSuchMethodError usually means you are compiling against the correct version of the google-cloud-datastore jar, but at runtime you have a different version. It would probably be more clear with the full stacktrace.
