### ISSUE TITLE
Map<String, Collection<?>> containing any empty collection is not stored in the Datastore

### ISSUE THREAD

**Issue by chrisbianca** [objectify/objectify#252] opened 2015-04-20 09:49 UTC
If you try and persist a Map<String, Collection<?>> where any key maps to an empty collection, then the whole map is not persisted to the Datastore.

e.g.
```
Map<String, Set<String>> theMap = new HashMap<String, Set<String>>();
theMap.put("1", new HashSet<String>());
theMap.get("1").add("test1");
		
theMap.put("2", new HashSet<String>());

WrapperObject wrapper = new WrapperObject(theMap);
ofy().save().entities(wrapper).now();
```

The reason for this is that:

1) CollectionTranslatorFactory throws a SkipException when it encounters the empty Set.
2) EmbeddedMapTranslatorFactory does not catch the SkipException so it bubbles up to PropertyPopulator.  
3) PropertyPopulator skips the entire property.

A simple change in EmbeddedMapTranslatorFactory at line 99 should fix this:

```
for (Map.Entry<Object, Object> entry: pojo.entrySet()) {
	String key = stringifier.toString(entry.getKey());
	Path propPath = path.extend(key);
	Object value = componentTranslator.save(entry.getValue(), index, ctx, propPath);

	DatastoreUtils.setContainerProperty(emb, key, value, index, ctx, propPath);
}
```

to:
```
for (Map.Entry<Object, Object> entry: pojo.entrySet()) {
	try {
		String key = stringifier.toString(entry.getKey());
		Path propPath = path.extend(key);
		Object value = componentTranslator.save(entry.getValue(), index, ctx, propPath);

		DatastoreUtils.setContainerProperty(emb, key, value, index, ctx, propPath);
	} catch (SkipException ex) {
		//do nothing
	}
}
```

**Comment by kleinerroemer** [comment] 2015-05-15 15:30
I have discovered a similar problem that might be related:

If you have:

````
@Index
@Stringify(IntegerStringifier.class)
private Map<Integer, Set<String>> data;
````

and do something like:
`````
data.put(0, new HashSet<String>());
data.put(1, new HashSet<String>());
data.get(1).add("somestring");
````
then no indizes are generated for data. In other words: If your map consits of integer keys that start higher than 0, no indizes are generated.

if I do:
`````
data.put(0, new HashSet<String>());
data.get(0).add("");
data.put(1, new HashSet<String>());
data.get(1).add("somestring");
````
it works fine.

**Comment by toyhunter** [comment] 2016-04-12 19:44
@chrisbianca Many thanks for great bug finding! I spent one day just to discover your post. My workaround, based on your finding, is never adding a key with empty collection. Cheers!

**Comment by kamronbatman** [comment] 2016-04-22 23:48
I ran into this problem with a Map<String, Map<Long, E>>.  Anyone able to look into fixing this?
I looked at how this was caused by haven't figured it out yet.

**Comment by tj-recess** [comment] 2016-04-23 01:06
I think the problem is when you use an interface type in your map's value type. Objectify doesn't know how to initialize it. So @kamronbatman - in your case, this would work
```java
Map<String, HashMap<Long, ConcreteType>>
```

Similar is the case with original problem.  While ```Map<String, Set<String>>``` doesn't work, ```Map<String, HashSet<String>>``` would work.

**Comment by kamronbatman** [comment] 2016-05-10 17:30
Thanks @tj-recess, I actually never though about it.
I ended up architecting my code differently, but if I come across this problem again, I'll try your suggestion and report back.

**Comment by jaichander** [comment] 2016-05-25 17:37
Been seeing strange behavior with my collections for a while, this seems to be the issue.
@stickfigure Whats the recommended work around for this at the moment?

Thank you.

**Comment by stickfigure** [comment] 2016-05-26 05:48
Wow I don't know where the year went or why I somehow overlooked this. I just committed the fix and pushed a 5.1.13 release. Sorry about the (long) delay.

**Closed by stickfigure** 2016-05-26 05:48 UTC
Labels: bug

**Comment by fantom075** [comment] 2018-01-03 17:45
I am using 5.1.21 and it looks like I'm having a very similar issue ?!

This is class MapEntity

```
import java.util.ArrayList ;
import java.util.HashMap ;
import java.util.Map ;
import com.googlecode.objectify.annotation.Entity ;
import com.googlecode.objectify.annotation.Id ;

@Entity
public class MapEntity
{
	@Id Long						id ;
	Map<String, ArrayList<String>>	map ;

	public MapEntity() {}

	public MapEntity(Long id, HashMap<String, ArrayList<String>> value) {
		this.id = id ;
		this.map = value ;
	}
}
```

Just testing the following does not save the "a" key into the Datastore while there is no pb if the testList is neither null nor empty

```
	private void testObjectifyMaps() {
		HashMap<String, ArrayList<String>> testMap ;
		ArrayList<String> testList ;
		testList = new ArrayList<String>() ;
		testMap = new HashMap<String, ArrayList<String>>() ;
		testMap.put("a", testList) ;
		MapEntity testMapEntity = new MapEntity(1L, testMap) ;
		ofy().save().entity(testMapEntity).now() ;
	}
```

Would you have any suggestion besides Objectify version ?

**Comment by stickfigure** [comment] 2018-01-03 21:11
I'm not seeing this problem... can you create a test with an assertion? I added a test with exactly this behavior to the v5 branch (identical code to 5.1.21) and it passes:

https://github.com/objectify/objectify/commit/342ab9defee3eb66a44293bcf47ca55a9f89aedc

**Comment by fantom075** [comment] 2018-01-03 21:13
Must have done something wrong. Quite late my time. Will check and tell you
tomorrow.

**Comment by fantom075** [comment] 2018-01-04 09:28
Oups, looks like it is the local Datastore viewer not displaying the entry
key but assert ok, will retry with my bigger project and let you know if
there is anything wrong

2018-01-03 22:13 GMT+01:00 Jimmy Lacerda <lacerda.jimmy@gmail.com>:
